name: Charge Monitor

on:
  schedule:
    - cron: '*/5 * * * *' # 每5分钟运行一次
  workflow_dispatch: # 允许手动触发

jobs:
  update-data:
    runs-on: ubuntu-latest
    timeout-minutes: 2 # 设置整个 Job 的超时时间为 2 分钟
    permissions:
      contents: write # 允许推送 commit

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run update script
      run: python update.py

    - name: Commit and push changes
      env:
        TZ: Asia/Shanghai
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add data/history.csv
        
        CURRENT_TIME=$(date "+%Y-%m-%d %H:%M:%S")
        
        if ! git diff --quiet || ! git diff --staged --quiet; then
          git commit -m "Auto-update charge data ($CURRENT_TIME)"
          git push
        else
          echo "No changes to commit"
        fi
